# Generated by Django 3.2.11 on 2026-03-29 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_auto_20220304_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='booking',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='auto_rejection_note',
            field=models.CharField(blank=True, default='', help_text='System-generated note when auto-rejected due to conflicting acceptance.', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_cancellation_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_cancellation_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Equipment breakdown'), (2, 'Personal/family emergency'), (3, 'Scheduling conflict / double booking'), (4, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Equipment not available on these dates'), (2, 'Equipment under maintenance/repair'), (3, 'Location too far'), (4, 'Booking duration too short/long'), (5, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text='Owner must respond before this time, otherwise booking auto-expires.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('AutoRejected', 'Auto Rejected'), ('Cancelled', 'Cancelled'), ('CancelledByOwner', 'Cancelled By Owner'), ('Expired', 'Expired'), ('Inprogress', 'Inprogress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
