# Generated by Django 3.2.11 on 2026-04-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_feedbackform_reportequipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancelform',
            options={'verbose_name': 'Cancellation Request', 'verbose_name_plural': 'Cancellation Requests'},
        ),
        migrations.AlterModelOptions(
            name='feedbackform',
            options={'verbose_name': 'User Feedback', 'verbose_name_plural': 'User Feedback'},
        ),
        migrations.AlterModelOptions(
            name='helpcentre',
            options={'verbose_name': 'Help Desk Enquiry', 'verbose_name_plural': 'Help Desk Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='partnerdispute',
            options={'verbose_name': 'Partner Dispute', 'verbose_name_plural': 'Partner Disputes'},
        ),
        migrations.AlterModelOptions(
            name='reportequipment',
            options={'verbose_name': 'Equipment Report', 'verbose_name_plural': 'Equipment Reports'},
        ),
    ]
