# Generated by Django 3.2.11 on 2026-04-11 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_auto_20260403_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancelform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cancellation Request', 'verbose_name_plural': 'Cancellation Requests'},
        ),
        migrations.AlterModelOptions(
            name='feedbackform',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Feedback', 'verbose_name_plural': 'User Feedback'},
        ),
        migrations.AlterModelOptions(
            name='helpcentre',
            options={'ordering': ['-created_at'], 'verbose_name': 'Help Desk Enquiry', 'verbose_name_plural': 'Help Desk Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='partnerdispute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Partner Dispute', 'verbose_name_plural': 'Partner Disputes'},
        ),
        migrations.AlterModelOptions(
            name='reportequipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Equipment Report', 'verbose_name_plural': 'Equipment Reports'},
        ),
        migrations.AddField(
            model_name='cancelform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At'),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At'),
        ),
        migrations.AddField(
            model_name='helpcentre',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At'),
        ),
        migrations.AddField(
            model_name='helpcentre',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='partnerdispute',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At'),
        ),
        migrations.AddField(
            model_name='partnerdispute',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='reportequipment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At'),
        ),
    ]
