# Generated by Django 3.2.11 on 2026-04-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': 'Equipment Category', 'verbose_name_plural': 'Equipment Categories'},
        ),
    ]
