# Generated by Django 3.2.11 on 2026-03-29 11:59

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user_1', '-updated_at'], name='chat_conver_user_1__9325b8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user_2', '-updated_at'], name='chat_conver_user_2__b98e14_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='chat_messag_convers_d0740f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='chat_messag_convers_7d694b_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(('user_1', django.db.models.expressions.F('user_2')), _negated=True), name='chat_no_self_conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('user_1', 'user_2'), name='chat_unique_conversation_pair'),
        ),
    ]
