# Generated by Django 3.2.11 on 2026-04-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_type', '0002_alter_equipmenttype_options'),
        ('brand', '0002_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='equipment_type',
            field=models.ManyToManyField(blank=True, help_text='Select which equipment categories this manufacturer produces. Only selected categories will appear when users list equipment for this brand.', to='equipment_type.EquipmentType'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='Manufacturer name (e.g. Mahindra, John Deere, TAFE)', max_length=200, unique=True),
        ),
    ]
