# Generated by Django 3.2.11 on 2026-03-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipmentrating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
