# Generated by Django 3.2.11 on 2026-04-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipment_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentrating',
            options={'verbose_name': 'Rating & Review', 'verbose_name_plural': 'Ratings & Reviews'},
        ),
    ]
