# Generated by Django 3.2.11 on 2026-04-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_backfill_eq_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='eq_id',
            field=models.CharField(editable=False, max_length=14, unique=True),
        ),
    ]
