# Generated by Django 3.2.11 on 2026-04-12 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_equipment_eq_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentrating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rating & Review', 'verbose_name_plural': 'Ratings & Reviews'},
        ),
        migrations.AddField(
            model_name='equipmentrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentrating',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='equipmentrating',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='equipment.equipment'),
        ),
    ]
